---

- name: add authorized_keys
  authorized_key:
    user: "{{ git_deploy_user.name }}"
    state: present
    key: "{{ item }}"
    key_options: "command=\"{{git_deploy_gitserve}}\",no-port-forwarding,no-agent-forwarding,no-X11-forwarding,no-pty"
  loop: "{{ git_deploy_authorized_keys|d([]) }}"
